/* Generated by Yosys 0.2.0+ (git sha1 d18c10d) */

module fsm(clk, rst, segA, segB, segC, segD, segE, segF, segG, segDP);
  wire [3:0] _000_;
  wire [1:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire [3:0] BCD;
  wire [7:0] SevenSeg;
  input clk;
  wire [1:0] cnt;
  input rst;
  output segA;
  output segB;
  output segC;
  output segD;
  output segDP;
  output segE;
  output segF;
  output segG;
  NOR2X1 _054_ (
    .A(cnt[0]),
    .B(rst),
    .Y(_001_[0])
  );
  NAND2X1 _055_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_002_)
  );
  NOR2X1 _056_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_003_)
  );
  NOR2X1 _057_ (
    .A(rst),
    .B(_003_),
    .Y(_004_)
  );
  AND2X2 _058_ (
    .A(_004_),
    .B(_002_),
    .Y(_001_[1])
  );
  XOR2X1 _059_ (
    .A(_002_),
    .B(BCD[0]),
    .Y(_005_)
  );
  NOR2X1 _060_ (
    .A(rst),
    .B(_005_),
    .Y(_000_[0])
  );
  INVX1 _061_ (
    .A(rst),
    .Y(_006_)
  );
  NAND2X1 _062_ (
    .A(BCD[1]),
    .B(_002_),
    .Y(_007_)
  );
  INVX1 _063_ (
    .A(BCD[1]),
    .Y(_008_)
  );
  NAND2X1 _064_ (
    .A(BCD[0]),
    .B(_008_),
    .Y(_009_)
  );
  OR2X2 _065_ (
    .A(_008_),
    .B(BCD[0]),
    .Y(_010_)
  );
  NAND2X1 _066_ (
    .A(_009_),
    .B(_010_),
    .Y(_011_)
  );
  INVX1 _067_ (
    .A(BCD[2]),
    .Y(_012_)
  );
  NAND2X1 _068_ (
    .A(BCD[3]),
    .B(_012_),
    .Y(_013_)
  );
  NOR2X1 _069_ (
    .A(_009_),
    .B(_013_),
    .Y(_014_)
  );
  NOR2X1 _070_ (
    .A(_002_),
    .B(_014_),
    .Y(_015_)
  );
  NAND2X1 _071_ (
    .A(_011_),
    .B(_015_),
    .Y(_016_)
  );
  NAND2X1 _072_ (
    .A(_007_),
    .B(_016_),
    .Y(_017_)
  );
  AND2X2 _073_ (
    .A(_017_),
    .B(_006_),
    .Y(_000_[1])
  );
  AND2X2 _074_ (
    .A(BCD[0]),
    .B(BCD[1]),
    .Y(_018_)
  );
  INVX1 _075_ (
    .A(_018_),
    .Y(_019_)
  );
  NOR2X1 _076_ (
    .A(_002_),
    .B(_019_),
    .Y(_020_)
  );
  XNOR2X1 _077_ (
    .A(_020_),
    .B(BCD[2]),
    .Y(_021_)
  );
  NOR2X1 _078_ (
    .A(rst),
    .B(_021_),
    .Y(_000_[2])
  );
  NAND2X1 _079_ (
    .A(BCD[3]),
    .B(_002_),
    .Y(_022_)
  );
  NOR2X1 _080_ (
    .A(BCD[3]),
    .B(_012_),
    .Y(_023_)
  );
  NAND2X1 _081_ (
    .A(_018_),
    .B(_023_),
    .Y(_024_)
  );
  NAND2X1 _082_ (
    .A(BCD[2]),
    .B(_018_),
    .Y(_025_)
  );
  NAND2X1 _083_ (
    .A(BCD[3]),
    .B(_025_),
    .Y(_026_)
  );
  NAND2X1 _084_ (
    .A(_024_),
    .B(_026_),
    .Y(_027_)
  );
  NAND2X1 _085_ (
    .A(_015_),
    .B(_027_),
    .Y(_028_)
  );
  NAND2X1 _086_ (
    .A(_022_),
    .B(_028_),
    .Y(_029_)
  );
  AND2X2 _087_ (
    .A(_029_),
    .B(_006_),
    .Y(_000_[3])
  );
  NOR2X1 _088_ (
    .A(BCD[2]),
    .B(BCD[3]),
    .Y(_030_)
  );
  NAND2X1 _089_ (
    .A(BCD[1]),
    .B(_030_),
    .Y(_031_)
  );
  NOR2X1 _090_ (
    .A(BCD[1]),
    .B(_013_),
    .Y(_032_)
  );
  INVX1 _091_ (
    .A(BCD[3]),
    .Y(_033_)
  );
  NAND2X1 _092_ (
    .A(BCD[2]),
    .B(_033_),
    .Y(_034_)
  );
  NOR2X1 _093_ (
    .A(_034_),
    .B(_010_),
    .Y(_035_)
  );
  OR2X2 _094_ (
    .A(_035_),
    .B(_032_),
    .Y(_036_)
  );
  NOR2X1 _095_ (
    .A(BCD[1]),
    .B(_034_),
    .Y(_037_)
  );
  NOR2X1 _096_ (
    .A(_037_),
    .B(_036_),
    .Y(_038_)
  );
  NAND2X1 _097_ (
    .A(_031_),
    .B(_038_),
    .Y(SevenSeg[1])
  );
  NOR2X1 _098_ (
    .A(BCD[0]),
    .B(BCD[1]),
    .Y(_039_)
  );
  NAND2X1 _099_ (
    .A(_030_),
    .B(_039_),
    .Y(_040_)
  );
  NAND2X1 _100_ (
    .A(_040_),
    .B(_038_),
    .Y(SevenSeg[2])
  );
  NAND2X1 _101_ (
    .A(_012_),
    .B(_039_),
    .Y(_041_)
  );
  OR2X2 _102_ (
    .A(_010_),
    .B(BCD[3]),
    .Y(_042_)
  );
  NAND2X1 _103_ (
    .A(_041_),
    .B(_042_),
    .Y(SevenSeg[3])
  );
  INVX1 _104_ (
    .A(_036_),
    .Y(_043_)
  );
  NOR2X1 _105_ (
    .A(_009_),
    .B(_034_),
    .Y(_044_)
  );
  AND2X2 _106_ (
    .A(_009_),
    .B(_030_),
    .Y(_045_)
  );
  NOR2X1 _107_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  NAND2X1 _108_ (
    .A(_046_),
    .B(_043_),
    .Y(SevenSeg[4])
  );
  NOR2X1 _109_ (
    .A(BCD[2]),
    .B(_010_),
    .Y(_047_)
  );
  NOR2X1 _110_ (
    .A(BCD[3]),
    .B(_047_),
    .Y(_048_)
  );
  OR2X2 _111_ (
    .A(_048_),
    .B(_032_),
    .Y(SevenSeg[5])
  );
  INVX1 _112_ (
    .A(_024_),
    .Y(_049_)
  );
  NOR2X1 _113_ (
    .A(_032_),
    .B(_049_),
    .Y(_050_)
  );
  OR2X2 _114_ (
    .A(_039_),
    .B(_012_),
    .Y(_051_)
  );
  NAND2X1 _115_ (
    .A(_033_),
    .B(_051_),
    .Y(_052_)
  );
  NAND2X1 _116_ (
    .A(_052_),
    .B(_050_),
    .Y(SevenSeg[6])
  );
  NOR2X1 _117_ (
    .A(_049_),
    .B(_036_),
    .Y(_053_)
  );
  NAND2X1 _118_ (
    .A(_046_),
    .B(_053_),
    .Y(SevenSeg[7])
  );
  BUFX2 _119_ (
    .A(SevenSeg[7]),
    .Y(segA)
  );
  BUFX2 _120_ (
    .A(SevenSeg[6]),
    .Y(segB)
  );
  BUFX2 _121_ (
    .A(SevenSeg[5]),
    .Y(segC)
  );
  BUFX2 _122_ (
    .A(SevenSeg[4]),
    .Y(segD)
  );
  BUFX2 _123_ (
    .A(1'b0),
    .Y(segDP)
  );
  BUFX2 _124_ (
    .A(SevenSeg[3]),
    .Y(segE)
  );
  BUFX2 _125_ (
    .A(SevenSeg[2]),
    .Y(segF)
  );
  BUFX2 _126_ (
    .A(SevenSeg[1]),
    .Y(segG)
  );
  DFFPOSX1 _127_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(cnt[0])
  );
  DFFPOSX1 _128_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(cnt[1])
  );
  DFFPOSX1 _129_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(BCD[0])
  );
  DFFPOSX1 _130_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(BCD[1])
  );
  DFFPOSX1 _131_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(BCD[2])
  );
  DFFPOSX1 _132_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(BCD[3])
  );
  assign SevenSeg[0] = 1'b0;
endmodule
